services:
    mysql8:
        image: mysql:8
        restart: always
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my_app
            MYSQL_USER: my_app
            MYSQL_PASSWORD: secret
        volumes:
            - ./:/application
        ports:
            - '9306:3306'

    cakephp:
        image: webdevops/php-apache:8.2
        container_name: cakephp
        working_dir: /application/webroot
        volumes:
            - ./:/application
        environment:
            - WEB_DOCUMENT_ROOT=/application/webroot
            - DATABASE_URL=mysql://my_app:secret@mysql/my_app
        ports:
            - "8099:80"
