services:
    mysql8:
        image: mysql:8
        restart: always
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: my_app
            MYSQL_USER: my_app
            MYSQL_PASSWORD: secret
        volumes:
            - ./:/application
        ports:
            - '9306:3306'

#    cakephp:
#        build:
#            dockerfile: php/Dockerfile
#        container_name: cakephp
#        working_dir: /application/webroot
#        volumes:
#            - ./:/application
#        environment:
#            - WEB_DOCUMENT_ROOT=/application/webroot
#            - DATABASE_URL=mysql://my_app:secret@mysql/my_app
#        ports:
#            - "8099:80"
#
    cakephp:
        build:
            dockerfile: php/Dockerfile
        container_name: cakephp
        working_dir: /application/webroot
        volumes:
            - ./:/application
        environment:
            - WEB_DOCUMENT_ROOT=/application/webroot
            - DATABASE_URL=mysql://my_app:secret@mysql/my_app
#        ports:
#            - "8099:80"

    web:
        build:
            dockerfile: apache/Dockerfile
#        image: httpd:2.4
        volumes:
            - ./:/application
        ports:
            - "8099:80"
        environment:
            - WEB_DOCUMENT_ROOT=/application/webroot
            - DATABASE_URL=mysql://my_app:secret@mysql/my_app
            - APACHE_RUN_USER=www-data
            - APACHE_RUN_GROUP=www-data
            - APACHE_PID_FILE=/var/run/apache2/apache2.pid
            - APACHE_RUN_DIR=/var/run/apache2
            - APACHE_LOCK_DIR=/var/lock/apache2
            - APACHE_LOG_DIR=/var/log/apache2

